---

- name: Install needed software
  package:
    name: nginx

- name: NGINX config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    force: true
  notify: reload nginx

- name: NGINX enabled and started
  service:
    name: nginx
    state: started
    enabled: true
