---

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Restart dnsmasq exporter
  service:
    name: dnsmasq_exporter
    state: restarted

- name: Reload Systemd
  systemd:
    daemon_reload: true

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
