---

- name: install prerequisites
  package:
    name:
      - apt-transport-https

- name: add grafana key
  apt_key:
    data: "{{ lookup('file', 'gpg.key') }}"

- name: add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: install grafana
  package:
    name: grafana

- name: configure grafana
  template:
    src: '{{ grafana_config }}'
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: '0600'
  notify:
    - restart grafana
  when: grafana_config is defined

- name: enable and start grafana
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Serve Grafana via nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ grafana_domain }}.conf
  notify: Reload nginx
  when: grafana_domain is defined
