---


- name: Reload Systemd
  systemd:
    daemon_reload: true

- name: Restart Blackbox Exporter
  service:
    name: blackbox_exporter
    state: restarted

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
