---

- name: Add prometheus user
  user:
    name: prometheus
    system: true

- name: Extract Node Exporter Sources
  unarchive:
    remote_src: true
    dest: /src/
    src: '{{ blackbox_exporter_download_path }}'
    creates: '{{ blackbox_exporter_src_path }}'

- name: Make directories present
  file:
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    state: directory

- name: Copy Binary
  copy:
    remote_src: true
    src: '{{ blackbox_exporter_src_path }}/blackbox_exporter'
    dest: /usr/bin/blackbox_exporter
    mode: 0755
  notify: Restart Blackbox Exporter

- name: Copy Config File
  copy:
    remote_src: true
    src: '{{ blackbox_exporter_src_path }}/blackbox.yml'
    dest: /etc/prometheus/blackbox.yml
  notify: Restart Blackbox Exporter
  when: blackbox_exporter_config is not defined

- name: Copy Config File
  template:
    src: '{{ blackbox_exporter_config }}'
    dest: /etc/prometheus/blackbox.yml
  notify: Restart Blackbox Exporter
  when: blackbox_exporter_config is defined

- name: Copy service file
  copy:
    src: blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service
  notify:
    - Reload Systemd
    - Restart Blackbox Exporter

- name: Enable and start Blackbox Exporter
  service:
    name: blackbox_exporter
    state: started
    enabled: true

- name: Create htpasswd
  htpasswd:
    path: /etc/nginx/blackbox_exporter.htpasswd
    name: '{{ blackbox_exporter_auth_user }}'
    password: '{{ blackbox_exporter_auth_password }}'
  notify: Reload nginx
  when: blackbox_exporter_auth_user is defined and blackbox_exporter_auth_password is defined

- name: Serve Blackbox Exporter via nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ blackbox_exporter_domain }}.conf
  notify: Reload nginx
  when: blackbox_exporter_domain is defined
