---

- name: Restart Node Exporter
  service:
    name: node_exporter
    state: restarted

- name: Reload Systemd
  systemd:
    daemon_reload: true

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
